name: Tests

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [10.4, 11.5]
        php: [7.3, 7.4, 8.0]
        exclude:
          - php: "8.0"
            typo3: "10.4"
          - php: "7.3"
            typo3: "11.5"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Prepare env
        run: export TYPO3_PATH_WEB="$PWD/.Build/Web"

      - name: Install dependencies
        run: composer require "typo3/cms-core:^${{ matrix.typo3 }}" "typo3/testing-framework"

      - name: Execute tests
        run: composer test

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install requirements
        run: composer global require --dev squizlabs/php_codesniffer --no-interaction

      - name: Execute php-cs-fixer checks
        run: ~/.composer/vendor/bin/php-cs-fixer fix --dry-run --config Resources/Private/Build/PhpCsFixer.php --cache-file=.Build/phpcs.cache

  messdetector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install requirements
        run: composer global require --dev phpmd/phpmd --no-interaction

      - name: Execute mess checks
        run: ~/.composer/vendor/bin/phpmd Classes/ text cleancode,codesize,controversial,design,naming --ignore-errors-on-exit --ignore-violations-on-exit
